remote_theme: dieghernan/chulapa
repository: dieghernan/RKI-Corona-Atlas

# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale                  : en-US
title                   : corona-atlas
title_separator         :     #default [" | "]
subtitle                :     #default [your-repository-tagline]
description             :  #default [your-repository-tagline]

timezone                :  Europe/Madrid

# SEO
og_image                :     ./assets/img/corona-atlas-icon.png
twitter_site            :     #Avoid @
author:
  name                  :  "Diego & Rodrigo"
  avatar                :     # Try a square file. Info: Your github avatar on https://github.com/[USERNAME].png
  location              :  "Berlin, Germany"   # New York, USA
#  links:
#    - url:  #A link or email: https://twitter.com/jack, mail@example.com
#      icon: # A Fontawesome 5 code: fab fa-twitter - see https://fontawesome.com/
#    - url:  # Another link
#      icon: # Anothet FontAwesome code

gtag_id                 :


# B. Navigation
# Configure your navbar and the footer of your site

# Navbar:
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  expand    :  always
  brand:
    title   :  corona-atlas # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  ./assets/img/corona-atlas-icon.svg
  nav:
  - title   : English # Label
    url     : /en # url
  - title   : Deutsch
    url     : /
  - title   : <i class="fab fa-github" aria-hidden="true"></i>
    url     : https://github.com/dieghernan/RKI-Corona-Atlas


# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 - url : https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap

# Theme and colors
chulapa-skin:
  highlight     :
  vars          :
    font-family-base: Roboto, sans-serif
    headings-font-family: Montserrat, sans-serif
    font-family-monospace: Roboto Mono, monospace
    white: white
    primary: "#1565c0"
    body-bg: white
    navbar-chulapa-bg-color: white
    navbar-chulapa-active-color: "#2962ff"
    footer-chulapa-icon-color: "#1565c0"
    footer-chulapa-icon-hover-color: transparent
    h1-font-size: 2.25rem
    h2-font-size: 1.5rem
    h3-font-size: 1.25rem
    h4-font-size: 1rem
    h5-font-size: 1rem
    h6-font-size: 1rem

# D. Jekyll Defaults and collections: see https://jekyllrb.com/





# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : /tags #This is where the link on tags would redirect
      cloudcategory_url   : /categories #This is where the link on categories would redirect

# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - '*.Rmd'

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

