remote_theme: dieghernan/chulapa
repository: dieghernan/RKI-Corona-Atlas
url: https://corona-atlas.de

# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale                  : de-DE
title                   : "Corona Atlas"
subtitle                :  "Internationale COVID-19 Risikogebiete im Überblick"
description             :  #default [your-repository-tagline]

timezone                :  Europe/Berlin

# SEO
og_image                :     ./assets/img/og_corona_atlas.png
twitter_site            : rodrihgh
author:
  name                  :  "Diego & Rodrigo"
  location              :  "Berlin, Germany"

gtag_id                 : "G-N81B7N0WSC"

comments:
  provider: disqus
  disqus_shortname: corona-atlas

# B. Navigation
navbar:
  style: dual
  brand:
    title   :  Corona Atlas # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  ./assets/img/corona-atlas-icon.svg
  nav:
  - title: Language
    img: ./assets/img/globe.svg
    child:
    - title   : Deutsch
      url     : /
    - title   : English # Label
      url     : /en # url
    - title   : Español # Label
      url     : /es # url
  - title   : About # Label
    url     : /about # url

footer:
  links:
    - label: "E-Mail"
      icon: "far fa-envelope"
      url:  "info@corona-atlas.de"
    - label: "GitHub"
      icon: "fab fa-github"
      url:  "https://github.com/dieghernan/RKI-Corona-Atlas"

# C. Theme Settings

chulapa-skin:
  skin          : academia

# D. Jekyll Defaults and collections: see https://jekyllrb.com/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      show_sociallinks  : true
      leaflet: true
      show_comments: true


# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - _R
  - '*.Rmd'
  - scrap
  - requirements.txt
  - scrapy.cfg

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

