# Move this file to .github/workflows/ folder
# Important: ALGOLIA_API_KEY should be set on Settings > Secrets
# Name: ALGOLIA_API_KEY
# Value: Your Algolia Admin API Key value (not be confused with Search-Only API Key)
# See https://github.com/marketplace/actions/algolia-jekyll-action

on:
  push:
    branches:
      - master
      - main

name: algolia-search
jobs:
  algolia-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            
      - name: Algolia Jekyll Action
        uses: dieghernan/algolia-jekyll-action@v1
        with:
          APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'
