---
title: "Corona Atlas Labs"
subtitle: "Heatmap"
permalink: /labs/heatmap
always_allow_html: yes
output: 
  md_document:
    preserve_yaml: true
---


<!-- Modify _R/labs file instead -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```



```{r data_cleansing, echo=FALSE}

library(giscoR)
library(sf)
library(readr)
library(dplyr)
library(countrycode)
library(leaflet)
library(reactable)
library(rmarkdown)
library(leaflet.providers)
library(leaflet.extras)

data <- readr::read_csv("../assets/data/db_scraped.csv")
rl <- readr::read_csv("../assets/data/risk_level_code.csv")
# %>%   mutate(risk_level_code = as.character(risk_level_code))



data_cntries <-
  data %>% filter(ISO3_CODE != "ERROR" & is.na(ERROR)) %>%
  filter(is.na(region)) %>%
  left_join(rl) %>%
  select(ISO3_CODE, NAME_ENGL, risk_date, risk_level_code, risk_level_en)

# EN - extract regions
regions <- data %>%
  filter(region == TRUE) %>%
  mutate(since = ifelse(is.na(risk_date),
                        "", paste0(", since ",
                       format(risk_date, "%d %b %Y")))) %>%
  group_by(ISO3_CODE) %>%
  mutate(regs = paste0("<li>", NAME_ENGL, since, "</li>", collapse = "")) %>%
  select(ISO3_CODE, regs) %>%
  distinct_all() %>%
  mutate(regs = paste0("<ul>", regs, "</ul>",
                       "More details in German or at ",
                       "<a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Risikogebiete_neu.html'>",
                       "rki.de</a>."))

# Add info

data_cntries <- data_cntries %>% left_join(regions)
data_cntries$more_info <- ifelse(is.na(data_cntries$risk_date),
                                 NA,
                                 paste0("Since ",
                                        format(data_cntries$risk_date, "%d %b %Y"),
                                        "."))

data_cntries$more_info <- ifelse(
  is.na(data_cntries$regs),
  data_cntries$more_info,
  paste0(
    data_cntries$more_info,
    " A different risk level may apply for the following regions: ",
    data_cntries$regs
  )
  
)

data_cntries$risk_date <-
  as.character(format(data_cntries$risk_date, format = "%d/%m/%Y"))

data_cntries$html_labels <- sprintf("<strong>%s</strong>",
                                    data_cntries$NAME_ENGL,
                                    data_cntries$risk_level_en)
data_cntries$html_labels <- ifelse(
  data_cntries$ISO3_CODE != "DEU",
  paste0(
    data_cntries$html_labels,
    "<br />",
    data_cntries$risk_level_en
  ),
  data_cntries$html_labels
)
#data_cntries$html_labels <- ifelse(!is.na(data_cntries$risk_date),
#                                   paste0(data_cntries$html_labels," seit ",data_cntries$risk_date),
#                                   data_cntries$html_labels
#                                   )

data_cntries$html_labels <- ifelse(
  !is.na(data_cntries$more_info),
  paste0(
    data_cntries$html_labels,
    "<p class='infomap'><strong>More information</strong><br />",
    data_cntries$more_info,
    "</p>"
  ),
  data_cntries$html_labels
)

data_cntries$html_labels <- data_cntries$html_labels %>% 
  lapply(htmltools::HTML)

date <- read.csv("../assets/data/report_date.csv") %>%
  select(report_date) %>% as.character() %>% 
  as.Date()


cntries_shape <-
  gisco_get_countries(
    year = 2020,
    epsg = 4326,
    cache_dir = "./geojson",
    resolution = 20
  )

# Add Kosovo
K <- st_read("./geojson/kosovo.geojson", quiet = TRUE) %>% select(ISO3_CODE)

cntries_shape_reg <-
  st_difference(cntries_shape, st_union(K))

cntries_shape_reg <- bind_rows(cntries_shape_reg, K)


cntries_shape_reg2 <- cntries_shape_reg %>%
  select(ISO3_CODE) %>%
  inner_join(data_cntries)

all_shapes <- st_make_valid(cntries_shape_reg2)

all_shapes <- all_shapes %>% select(ISO3_CODE) %>% left_join(data_cntries)


```

<p class="text-right font-weight-bold">Updated on `r format(date, format="%d %B %Y")`</p>

## Labs - Heatmap


```{r map, echo=FALSE, out.width = "100%", out.height="75vh"}



coords <-
  st_centroid(all_shapes, of_largest_polygon = TRUE) %>% st_coordinates() %>%
  as.data.frame()

heat <- st_drop_geometry(all_shapes) %>% cbind(coords)
heat$risk_level_code2 <- NA
heat$risk_level_code2 <- ifelse(heat$risk_level_code == 1,
                                4, heat$risk_level_code2)
heat$risk_level_code2 <- ifelse(heat$risk_level_code == 2,
                                3, heat$risk_level_code2)
heat$risk_level_code2 <- ifelse(heat$risk_level_code == 3,
                                2, heat$risk_level_code2)
heat$risk_level_code2 <- ifelse(heat$risk_level_code == 4,
                                1, heat$risk_level_code2)
heat$risk_level_code2 <- ifelse(heat$risk_level_code == 0,
                                0, heat$risk_level_code2)

heat$risk_level_code2 <- heat$risk_level_code2 + 1
leaflet(heat, options = leafletOptions(minZoom = 1.5),
        elementId = "leaflet") %>%
  setMaxBounds(-180,-80, 180, 80) %>%
  addProviderTiles("CartoDB.DarkMatter") %>%
  addHeatmap(
    lat = ~ Y,
    lng = ~ X,
    intensity = ~ risk_level_code2 ,
    max = 5,
    radius = 20
  )  %>%
  addCircleMarkers(
    stroke = FALSE,
    fillColor = NA,
    fillOpacity = 0,
    lat = ~ Y,
    lng = ~ X,
    popup = heat$html_labels
  ) %>%
  setView(lat = 51.705533, lng = 11.8124408, zoom = 4) %>%
  addEasyButton(
    easyButton(
      icon = "fa-globe",
      title = "",
      onClick = JS(
        "function(btn, map){ map.setView([ 51.705533,11.8124408],4); }"
      )
    )
  )


```

