---
title: "Untitled"
subtitle: aaa
permalink: /test
always_allow_html: yes
output: 
  md_document:
    preserve_yaml: true
---


<!-- Modify _R/*.Rmd file instead -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```


## Including Code



```{r test, echo=FALSE}

library(giscoR)
library(sf)
library(readr)
library(dplyr)
library(countrycode)
library(leaflet)
library(reactable)
library(rmarkdown)
library(leaflet.providers)

data <- readr::read_csv("../assets/data/db_countries.csv")
rl <- readr::read_csv("../assets/data/risk_level_code.csv")


cntries_shape <-
  gisco_get_countries(
    year = 2020,
    epsg = 4326,
    cache_dir = "../assets/data/geojson",
    resolution = 60
  )

# Get NUTS units
data_units <- data %>% filter(region == TRUE & !is.na(NUTS_CODE))


nuts_shape <- gisco_get_nuts(
  year = 2021,
  epsg = 4326,
  cache_dir = "../assets/data/geojson",
  resolution = 60,
  nuts_id = data_units$NUTS_CODE
)

nuts_shape_end <- nuts_shape %>%
  mutate(NUTS_CODE = NUTS_ID,
         name.en = NAME_LATN,
         name.de = NAME_LATN) %>%
  select(NUTS_CODE, name.en, name.de) %>% inner_join(data_units) %>%
  select(ISO3_CODE, name.en, name.de, risk_level_code)

# Get LAU
data_lau <-
  data_units %>% filter(!NUTS_CODE %in% nuts_shape$NUTS_ID)

lau_shape <- gisco_get_lau(
  year = 2019,
  epsg = 4326,
  cache_dir = "../assets/data/geojson",
  gisco_id = data_lau$NUTS_CODE
)

lau_shape_end <- lau_shape %>%
  mutate(NUTS_CODE = GISCO_ID,
         name.en = LAU_NAME,
         name.de = LAU_NAME) %>%
  inner_join(data_units) %>%
  select(ISO3_CODE, name.en, name.de, risk_level_code)

regions_end <-
  bind_rows(nuts_shape_end, lau_shape_end) %>% mutate(region = TRUE)


# Substract regions from countries

cntries_shape_reg <-
  st_difference(cntries_shape, st_union(regions_end))

data_cntries <- data %>% filter(is.na(region)) %>%
  mutate(name.en = NAME_ENGL,
         name.de = countrycode(ISO3_CODE, "iso3c", "cldr.name.de")) %>%
  select(ISO3_CODE, name.en, name.de, risk_level_code) %>% distinct() %>%
  mutate(name.de = ifelse(is.na(name.de),
                          name.en,
                          name.de))



cntries_shape_reg2 <- cntries_shape_reg %>%
  select(ISO3_CODE) %>%
  inner_join(data_cntries)

all_shapes <- bind_rows(cntries_shape_reg2, regions_end)
all_shapes <- st_make_valid(all_shapes)

df_labels <- data_cntries %>% mutate(cntry.en = name.en,
                                     cntry.de = name.de) %>%
  select(ISO3_CODE, cntry.en, cntry.de)

# Labels
all_shapes <- all_shapes %>% left_join(df_labels)

all_shapes$label_en <- ifelse(
  !is.na(all_shapes$region),
  paste0(all_shapes$cntry.en, " | ", all_shapes$name.en),
  all_shapes$name.en
)
all_shapes$label_de <- ifelse(
  !is.na(all_shapes$region),
  paste0(all_shapes$cntry.de, " | ", all_shapes$name.de),
  all_shapes$name.de
)

all_shapes <-
  all_shapes %>% select(ISO3_CODE, label_en, label_de, risk_level_code) %>% mutate(risk_level_code = as.integer(risk_level_code)) %>% left_join(rl) 
#------


DEU <- all_shapes %>% filter(ISO3_CODE == "DEU")
level0 <- all_shapes %>% filter(risk_level_code == "0",
                                ISO3_CODE != "DEU")
level1 <- all_shapes %>% filter(risk_level_code == "1")
level2 <- all_shapes %>% filter(risk_level_code == "2")
level3 <- all_shapes %>% filter(risk_level_code == "3")
level4 <- all_shapes %>% filter(risk_level_code == "4")

```


## This is the map
```{r map, echo=FALSE, out.width = "100%", out.height="60vh"}


map <- leaflet(options = leafletOptions(minZoom = 0.5)) %>%
  setMaxBounds(-180, -90, 180, 90) %>%
  # addProviderTiles("CartoDB.Voyager") %>%
  setView(lat = 51.705533, lng = 11.8124408, zoom = 4) %>%
  addPolygons(data = DEU, 
              stroke = FALSE,  
              smoothFactor = 0.3,
              fillColor = "blue",
              fillOpacity = 0.5) %>%
  addPolygons(data = level0,
              stroke = FALSE,
              smoothFactor = 0.3,
              fillColor = "green",
              fillOpacity = 0.5) %>%
  addPolygons(data = level1,
              stroke = FALSE,
              smoothFactor = 0.3,
              fillColor = "red",
              fillOpacity = 0.5) %>%
  addPolygons(data = level2,
              stroke = FALSE,
              smoothFactor = 0.3,
              fillColor = "orange",
              fillOpacity = 0.5) %>%
    addPolygons(data = level3,
              stroke = FALSE,
              smoothFactor = 0.3,
              fillColor = "yellow",
              fillOpacity = 0.5) %>%
    addPolygons(data = level4,
              stroke = FALSE,
              smoothFactor = 0.3,
              fillColor = "#00FF00",
              fillOpacity = 0.5) %>%
  addEasyButton(easyButton(
                           icon = "fa-globe",
                           title = "Zoom to Level 1",
                           onClick = JS(
                             "function(btn, map){ map.setView([ 51.705533,11.8124408],4); }"
                           )
                         ))

map
```



## A Table

And this is the table

<script src="https://cdn.jsdelivr.net/gh/dieghernan/RKI-Corona-Atlas/_R/plugins/reactable-binding-0.2.3/reactable.min.js"></script>
```{r table , echo=FALSE}


df <- st_drop_geometry(all_shapes)

reactable(df,
          filterable = TRUE,
          searchable = TRUE,
          showPageSizeOptions = TRUE,
          striped = TRUE,
          paginationType = "jump"
          )

```

