name: corona-atlas

on:
 push:
   branches:
     - master
     - main
   paths:
     - _R/**
     - assets/data/**
     - .github/workflows/**
 pull_request:
   branches:
     - master
     - main
   paths:
     - _R/**
     - assets/data/**
 schedule:
   - cron: "0 5/6 * * *"
 workflow_dispatch:
jobs:
  corona-atlas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v3.2.2
        name: Cache Python dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install German locale
        run: sudo apt-get update && sudo apt-get install language-pack-de

      - name: Scrap data
        run: |
          cp -R assets/data log/data
          scrapy crawl rki > log/scrapy_report.txt
          cat log/scrapy_report.txt
          diff log/data assets/data || echo '::set-output name=DATABASE::NEW'
        id: scrapy

      - uses: r-lib/actions/setup-r@v2
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        name: Setup R
        with:
          r-version: '4.1.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        name: Setup Pandoc
        with:
          pandoc-version: '2.7.3'

      - name: Send mail
        uses: dawidd6/action-send-mail@v3.4.1
        if: steps.scrapy.outputs.DATABASE == 'NEW'
        with:
          server_address: smtp.ionos.de
          server_port: 465
          username: info@corona-atlas.de
          password: ${{secrets.MAIL_PW}}
          subject: RKI-Corona-Atlas new data
          to: ${{secrets.MAIL_DH}},${{secrets.MAIL_RH}}
          from: Corona Atlas
          body: |
            The database of the repo RKI-Corona-Atlas has been updated with the newest data from https://rki.de/risikogebiete .
            Check the result at https://corona-atlas.de

            More details in the attachment.
          ignore_cert: true
          attachments: log/scrapy_report.txt,assets/data/db_scraped.csv

      - name: Install additional libraries for R
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        run: sudo apt-get update && sudo apt-get install libmagick++-dev libcurl4-openssl-dev libudunits2-dev gdal-bin proj-bin libgdal-dev libproj-dev libharfbuzz-dev libfribidi-dev


      - name: Restore R packages
        uses: r-lib/actions/setup-renv@v2
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'

      - name: Create maps
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        run: Rscript _R/trigger.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'corona-atlas update' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

