name: corona-atlas

on:
 push:
   branches:
     - master
     - main
   paths:
     - _R/**
     - assets/data/**
 pull_request:
   branches:
     - master
     - main
   paths:
     - _R/**
     - assets/data/**
 schedule:
   - cron: "0 5/6 * * *"

jobs:
  corona-atlas:
    runs-on: ubuntu-latest
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - uses: actions/cache@v2
        name: Cache Python dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install German locale
        run: sudo apt-get update && sudo apt-get install language-pack-de

      - name: Scrap data
        run: |
          cp -R assets/data log/data
          scrapy crawl rki > log/scrapy_report.txt
          cat log/scrapy_report.txt
          diff log/data assets/data || echo '::set-output name=DATABASE::NEW'
        id: scrapy
        
      - uses: r-lib/actions/setup-r@v1
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        name: Setup R
        
      - uses: r-lib/actions/setup-pandoc@master
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        name: Setup Pandoc
        
      - uses: actions/cache@v2
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        name: Cache R dependencies
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv2-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv2-
            
      - name: Install libdunits
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        run: sudo apt-get install libudunits2-dev

      - name: Install gdal
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        run: sudo apt-get install gdal-bin proj-bin libgdal-dev libproj-dev

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        if: steps.scrapy.outputs.DATABASE == 'NEW'
        with:
          server_address: smtp.ionos.de
          server_port: 465
          username: info@corona-atlas.de
          password: ${{secrets.MAIL_PW}}
          subject: RKI-Corona-Atlas new data
          to: ${{secrets.MAIL_DH}},${{secrets.MAIL_RH}}
          from: Corona Atlas
          body: |
            The database of the repo RKI-Corona-Atlas has been updated with the newest data from https://rki.de/risikogebiete .
            Check the result at https://corona-atlas.de

            More details in the attachment.
          ignore_cert: true
          attachments: log/scrapy_report.txt,assets/data/db_scraped.csv

      - name: Restore R packages
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Create maps
        if: github.event_name != 'schedule' || steps.scrapy.outputs.DATABASE == 'NEW'
        run: Rscript _R/trigger.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'corona-atlas update' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
        # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        name: Jekyll cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
 
      - uses: helaili/jekyll-action@2.2.0
        name: Build page - source code on branch gh-pages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'



