name: daily-gif

on:
  workflow_dispatch:

  schedule:
   - cron: "0 1 * * *"


jobs:
  daily-gif:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2
        name: Setup Pandoc
        with:
          pandoc-version: '2.7.3'

      - name: Install additional libraries for R
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libudunits2-dev gdal-bin proj-bin libgdal-dev libproj-dev libharfbuzz-dev libfribidi-dev


      - name: Restore R packages
        uses: r-lib/actions/setup-renv@v2


      - name: Clean and recreate
        run: |
          Rscript _R/create_gif.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Update page' || echo "No changes to commit"
          git push origin || echo "No changes to commit"


