# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: scrap-rki

on: workflow_dispatch # TODO schedule

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev  # TODO master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install German locale
      run: sudo apt-get update && sudo apt-get install language-pack-de
    - name: Execute scrap script
      run: |
        cp -R assets/data log/data
        scrapy crawl rki &> log/scrapy_report.txt
        cat log/scrapy_report.txt
        diff log/data assets/data || echo '::set-output name=DATABASE::NEW'
      id: scrapy
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      if: steps.scrapy.outputs.DATABASE == 'NEW'
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_RH}}
        password: ${{secrets.MAIL_PW}}
        subject: RKI-Corona-Atlas new data
        to: ${{secrets.MAIL_DH}},${{secrets.MAIL_RH}}
        from: GitHub Actions
        body: The database of the repository RKI-Corona-Atlas has been updated with the newest data from the RKI. More details in the attachment.
        ignore_cert: true
        attachments: log/scrapy_report.txt,assets/data/db_scrapped.csv
    - name: Commit results
#      if: steps.scrapy.outputs.DATABASE == 'NEW'
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add assets/data
        git commit -m 'database updated' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
