# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: scrap-rki

on: workflow_dispatch # TODO schedule

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev  # TODO master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute scrap script
      run: scrapy crawl rki > scrap/log.out
      # TODO send log.out e-mail if new data
    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -m 'corona-atlas update' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
