name: update-page

on: workflow_dispatch 

jobs:
  update-page:
    runs-on: ubuntu-latest
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        name: Cache Python dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install German locale
        run: sudo apt-get update && sudo apt-get install language-pack-de

      - name: Scrap data
        run: |
          cp -R assets/data log/data
          scrapy crawl rki > log/scrapy_report.txt
          cat log/scrapy_report.txt
          diff log/data assets/data || echo '::set-output name=DATABASE::NEW'
        id: scrapy

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'hotfix-test' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
